### PR TITLE
Upgrade to Appwrite 1.0

### LINKED ISSUE #4272: 🪄 Upgrade ’demo-todo-with-vue’ to Appwrite 1.0
# 💭 Introduction

Appwrite is all about open source and community 👥 To emphasize this, we want to create **the best** developer experience possible by providing enough guides and examples for new Appwriters.

Your task is to upgrade our demo application **appwrite/demo-todo-with-vue** to the latest Appwrite version, which is 1.0. All of the functionality of the demo application must stay the same. 

### ✅ Task Summary

- [ ]  Ask to be assigned to the issue.
- [ ]  Wait to be assigned.
- [ ]  Upgrade appwrite/demo-todo-with-vue to support Appwrite 1.0.
- [ ]  Submit a pull request in **appwrite/demo-todo-with-vue**.

If you have questions, need any help, or just want to hang out, make sure to join us on our [Discord server](https://appwrite.io/discord).

**Happy Appwriting!**

### PR DESCRIPTION
**Pull request by chirag-ghosh**
## What does this PR do?

This PR upgrades the vue-demo app to Appwrite 1.0

## Test Plan

I setup an appwrite server using gitpod and ran the demo locally. I fixed the code to use Appwrite 1.0 and tested all the functions.

## Related PRs and Issues
 [Issue in main repo](https://github.com/appwrite/appwrite/issues/4272)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

### CODE REVIEW

**Comment by Meldiron** [comment]
@chirag-ghosh , thanks for the PR! 🤯 Please give us some time to review it.

**Comment by chirag-ghosh** [comment]
@Meldiron I understand the need for review. However, can you atleast label it "hacktoberfest-accepted" ?

**Review by stnguyen90 — APPROVED** [review]
@chirag-ghosh Hey 👋 awesome work on your PR! We've approved your work and it'll be merged soon!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
